# Generated by Django 3.0.6 on 2020-05-18 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
