# Generated by Django 3.0.6 on 2020-05-19 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_order_order_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='update_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Last Updated'),
        ),
    ]
